apiVersion: v1
kind: Service
metadata:
  name: my-service-loadbalancer
spec:
  selector:
    app: my-app
  externalIPs:
    - 192.168.1.100 # Node IP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
